* wifi-entries-setup
  =wifi-entries-setup= is the shell-script program which adds the new Wi-Fi entry
  to assigned configuration file (ex. =wpa_supplicant.conf=)
  using =wpa_passphrase=.
  # To my knowledge interactive program =wpa_cli= attached with =wpa_supplicant=
  # can update the file, but it refreshes already registed entries.

** Requirements
   It requires the following Wi-Fi confuguration program.
   - [[https://w1.fi/wpa_supplicant/][wpa_supplicant]]

** Install
   Download and modify the path of the configuration file
   (default: =/etc/wpa_supplicant/wpa_supplicant.conf=) in =wifi-entries-setup=.
   #+BEGIN_SRC sh
   $ git clone https://github.com/kkatsuyuki/wifi-entries-setup.git
   $ cd wifi-entries-setup
   #+END_SRC

   Edit =wifi-entries-setup= to adjust =CONFIG_FILE= to your environment.
   #+BEGIN_SRC sh
   CONFIG_FILE=/to/yourpath/wpa_supplicant.conf
   #+END_SRC

   Edit =wifi-entries-setup= to select an =INTERFACE= for your system
   #+BEGIN_SRC sh
   INTERFACE="wlp2s0"
   #+END_SRC

   Then move this executable =wifi-entries-setup= file to the directory included in =$PATH= (usually =/usr/bin/=).
   #+BEGIN_SRC sh
   $ cp wifi-entries-setup /usr/bin/
   #+END_SRC

** Usage
   #+BEGIN_EXAMPLE
   Usage: wifi-entries-setup [-h]
   #+END_EXAMPLE

   Get the root privilege and execute =wifi-entries-setup=.
   Input SSID and Passphrase (optional) interactively following the prompt.
   - Passphrase is not given, then the entry is registered as the open network.
   - If the command executed with =-h= option, the help message is appeared.

   *Example*

   Add the wireless network whose SSID and passphrase are "foo" and "foobarbaz", respectively.
   #+BEGIN_EXAMPLE
   # wifi-entries-setup
   Starting to scan WiFi ...
   0: foo
   1: bar
   2: baz

   Which SSID is registered? (input by No.) > 0
   Input passphrase (default NONE) > foobarbaz
   Protected Wifi network
   SSID foo was registered and you can connect.
   #+END_EXAMPLE

** How to connect the Wi-Fi after registered
   The followings are refered to [[https://wiki.archlinux.org/index.php/Wireless_network_configuration][Wireless network configuration]] on ArchWiki.

   If necessary, make the Wi-Fi interface enabled at first.
   #+BEGIN_EXAMPLE
   # ip link set <interface> up
   #+END_EXAMPLE

   Then get the authentification and IP address from the wireless network.
   #+BEGIN_EXAMPLE
   # wpa_supplicant -B -i <interface> -c /to/yourpath/wpa_supplicant.conf
   # dhcpcd -b <interface>
   #+END_EXAMPLE

** References
   I refered to the following to make this source code.
   - [[https://stackoverflow.com/questions/10582763/how-to-return-an-array-in-bash-without-using-globals/15982208#15982208][How to return an array in bash without using globals?]]
