#+BEGIN_EXPORT html
---
layout: default
---
#+END_EXPORT
* Motivation
  Using =wpa_supplicant= as the authetification software of Wi-Fi network,
  every time I connect the new network, I have to edit its configuration file
  (ex. =wpa_supplicant.conf=). Editing it manually is very time-consuming for me,
  So I made the shell-script program =addWifi= to add the new Wi-Fi entry to
  the assigned configuration file.

* Features
  - Input Wi-Fi entry (=SSID=, =[Passphrase]=) are added to the assigned configuration 
    file (ex. =wpa_supplicant.conf=)
  - On root priviledge input SSID and Passphrase (optional) interactively following the prompt

* Usage
  #+BEGIN_EXAMPLE
  Usage: addWifi [-h]
  #+END_EXAMPLE

  Get the root privilege and execute =addWifi=. 
  Input the SSID and Passphrase (optional) interactively following the prompt.
  - Passphrase is not given, then the entry is registered as the open network.
  - If the command executed with =-h= option, the help message is appeared.
    
    
  *Example*

  Add the wireless network whose SSID and passphrase are "foo" and "foobarbaz", respectively.
  #+BEGIN_EXAMPLE
  # addWifi
  Staring to scan WiFi ...
  0: foo
  1: bar
  2: baz

  Which SSID is registered? (input by No.) > 0
  Input passphrase (default NONE) > foobarbaz
  Protected Wifi network
  SSID foo was registered and you can connect.
  #+END_EXAMPLE

* Install
  Refer to [[https://github.com/kkatsuyuki/addWifi][README]].

